# Change these first
owner: toll # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: MO - movement-road-api-v2
    url: https://api.toll.no/api/movement/road/v2/swagger-ui/index.html
    logoUrl: https://raw.githubusercontent.com/toll/toll-api-status/master/extra-images/toll-logo.jpg
  - name: MO - movement-road-query-api-v2
    url: https://api.toll.no/api/movement/road/status/v2/swagger-ui/index.html
  - name: MO - movement-air-api
    url: https://api.toll.no/api/movement/air/v1/swagger-ui/index.html
  - name: MO - movement-air-query-api
    url: https://api.toll.no/api/movement/air/status/v1/swagger-ui/index.html
  - name: MO - movement-rail-api
    url: https://api.toll.no/api/movement/rail/v1/swagger-ui/index.html
  - name: MO - movement-rail-query-api
    url: https://api.toll.no/api/movement/rail/status/v1/swagger-ui/index.html
  - name: MO - movement-presentation-api
    url: https://api.toll.no/api/movement/presentation/v1/swagger-ui/index.html
  - name: MO - movement-routing-api
    url: https://api.toll.no/api/movement/routing/v1/swagger-ui/index.html

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/toll/toll-api-status/master/extra-images/toll-logo.jpg
  favicon: https://raw.githubusercontent.com/toll/toll-api-status/master/extra-images/toll-logo.jpg
  name: Tolletaten
  introTitle: Oversikt over livssyklusen til Tolletaten sine tjenester til eksterne API-brukere.
  introMessage: Tolletatens data- og API-dokumentasjon finner du [her:](https://toll.github.io/)  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
