# Change these first
owner: toll # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Tolletaten
    url: https://www.toll.no
    icon: https://www.toll.no/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/toll/toll-api-status/master/extra-images/toll-logo.jpg
  favicon: https://raw.githubusercontent.com/toll/toll-api-status/master/extra-images/toll-logo.jpg
  name: Tolletaten
  introTitle: Status for Tolletatens eksterne API-er
  introMessage: Tolletatens data- og API-dokumentasjon finner du [**her.**](https://toll.github.io/)
  # Increasing cache time from 2 min to 30 min to make it less likely running into rate limiting issues
  productionCacheTime: 1800000
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
